version: '3.8'

services:
  nginx:
    build: .  # Esto construirá el contenedor de Nginx, que también contendrá la aplicación Angular
    ports:
      - "80:80"  # Nginx escuchando en el puerto 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: front-admin-container  
