version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    container_name: front-admin-container  # Aquí defines el nombre del contenedor
