name: Deploy Angular App Testing

on:
  workflow_run:
    workflows: ["ANGULAR CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}  # Solo se ejecuta si 'ANGULAR CI' fue exitoso y en 'main'
    
    steps:
    - name: Comprobando el repositorio
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: '10.43.100.240'
        username: 'estudiante'
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          /home/estudiante/Desktop/deploy.sh
