name: Deploy Angular App to Testing

on:
  workflow_run:
    workflows: ["ANGULAR CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, test-admin]  # Runner local para 'testing'
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}  # Solo se ejecuta si 'ANGULAR CI' fue exitoso y en 'main'
    
    steps:
    - name: Comprobando el repositorio
      uses: actions/checkout@v4

    - name: Ejecutar el script de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.DEPLOY_SSH_KEY_TESTING }} estudiante@10.43.101.107 'bash -s' < ./deploy.sh

    - name: Comprobar estado de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.DEPLOY_SSH_KEY_TESTING }} estudiante@10.43.101.107 'docker ps'
