name: Deploy Angular App to Production

on:
  workflow_run:
    workflows: ["Deploy Angular App to Testing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, prod-admin]  # Runner local para 'producción'
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
    - name: Esperando aprobación manual
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: ''  # Sin especificar aprobadores, cualquier miembro con acceso puede aprobar
        minimum-approvals: 2  # Se requieren al menos 2 aprobaciones
        issue-title: "Desplegando a producción"
        issue-body: "Por favor, aprueba o niega el despliegue a producción."
        exclude-workflow-initiator-as-approver: true  # El iniciador del workflow no puede aprobar

    - name: Comprobando el repositorio
      uses: actions/checkout@v4

    - name: Configurar el agente SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY_PRODUCTION }}

    - name: Ejecutar el script de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.240 'bash -s' < ./deploy.sh production
      working-directory: ./  # Establece el directorio de trabajo a la raíz del repositorio

    - name: Comprobar estado de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.240 'docker ps'
